mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: a111111
    db: wild_goose_gin
    log_level: info
redis:
    addr: localhost:6379
    password: a111111
    db: 1
logger:
    show_pass_line: true
server:
    host: 127.0.0.1
    port: "8888"
    env: dev
site_info:
    created_at: 2023.7.29
    bei_an: 川 xxxxx
    title: 鸿雁后台管理系统
    addr: 成都
qq:
    app_id: "666"
    key: dadd
    redirect: aaa
qi_niu:
    enable: false
    access_key: PkIfo3U5fGsC5tgiT2RHWEsVwU-bz6-vApT1rUkH
    secret_key: Dj3o1YUJSboe3N6oefpOyqyOyzryi6PV4A9cZIOz
    bucket: blog-gin-lihao
    cdn: www.lihao_blog.com
    zone: z2
    size: 1
    prefix: gin_blog
email:
    from: 1039007652@qq.com
    host: smtp.qq.com
    port: 587
    password: xegrxgvkminlbcbh
jwt:
    secret: your_secret_key
    expires: 6000
    issuer: your_app_name
upload:
    size: 1
    path: uploads/file
    white_list:
        - .jpg
        - .jpeg
        - .png
es:
    host: http://127.0.0.1
    port: 9200
